steps:
# Install test node modules
- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  dir: server
  env: ["NODE_ENV=development"]
  args: ["install"]

# Run unit tests
- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  dir: server
  args: ["test"]

# Build docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --tag
  - asia.gcr.io/$PROJECT_ID/fibonacci-server:$BUILD_ID
  - server

# Start Fibonacci server that we just built
- name: 'docker/compose:1.23.2'
  env:
  - "IMAGE=asia.gcr.io/$PROJECT_ID/fibonacci-server:$BUILD_ID"
  - "PORT=8080"
  args: ["up", "--detach", "waiter"]

# # Test the Fibonacci server's endpoint
- name: 'gcr.io/cloud-builders/curl'
  entrypoint: /bin/sh
  args:
  - -c
  - |
    request () {
      OUTPUT=$$(curl --silent --fail http://fibonacci-server:8080/?n="$$1") || exit
    }
    request 0; [ "$$OUTPUT" = 'The 0th Fibonacci number is 0!' ] || exit
    request 1; [ "$$OUTPUT" = 'The 1st Fibonacci number is 1!' ] || exit
    request 2; [ "$$OUTPUT" = 'The 2nd Fibonacci number is 2!' ] || exit

images:
- asia.gcr.io/$PROJECT_ID/fibonacci-server:$BUILD_ID

