steps:
# Install node modules
- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  dir: server
  env: ["NODE_ENV=development"]
  args: ["install"]

# Run unit tests
- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  dir: server
  args: ["test"]

# Build docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --tag
  - asia.gcr.io/$PROJECT_ID/fibonacci-server:$BUILD_ID
  - server

# Start Fibonacci server that we just built
- name: 'docker/compose:1.23.2'
  env:
  - "IMAGE=asia.gcr.io/$PROJECT_ID/fibonacci-server:$BUILD_ID"
  - "PORT=8080"
  args: ["up", "--detach", "waiter"]

# Test the Fibonacci server's endpoint
- name: 'gcr.io/cloud-builders/curl'
  entrypoint: /workspace/server/api_tests.sh
  
options:
  machineType: N1_HIGHCPU_8
  # machineType: N1_HIGHCPU_32 # 30GB memory and 32 CPUs
  
  # diskSizeGb: 1000GB # <= 1TB

images:
- asia.gcr.io/$PROJECT_ID/fibonacci-server:$BUILD_ID
