steps:
- name: gcr.io/cloud-builders/kubectl
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=fibonacci-cluster'
  args:
  - apply
  - -f
  - cd/deployment.yaml
