steps:
# Install node modules
- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  dir: nodejs
  env: ["NODE_ENV=development"]
  args: ["install"]

# Run unit tests
- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  dir: nodejs
  args: ["test"]

# Build docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --tag
  - fibonacci-server:latest
  - nodejs

# Start Fibonacci server that we just built
- name: 'docker/compose:1.23.2'
  dir: ci
  env:
  - 'IMAGE=fibonacci-server:latest'
  args: ["up", "--detach", "waiter"]

# Test the Fibonacci server's endpoint
- name: 'gcr.io/cloud-builders/curl'
  entrypoint: /bin/sh
  args: ["/workspace/ci/api_tests.sh"]
