version: '2.1'
services:
  fibonacci-server:
    container_name: fibonacci-server 
    image: $IMAGE
    environment:
    - PORT=8080
    healthcheck:
      test:
      - CMD-SHELL
      - 'curl --fail http://localhost:$PORT/?n=0 || exit 1'
      interval: 5s
      timeout: 1s
    ports:
      - '8080:8080'

  # Helper service that will wait until fibonacci-server is ready to accept requests
  waiter:
    image: busybox
    depends_on:
      fibonacci-server:
        condition: service_healthy

# Join network created by Cloud Build so that API tests can find the container by it's
# name (fibonacci-server).
networks:
    default:
        external:
            name: cloudbuild